export const LIST_SERVICES_REQUEST = "LIST_SERVICES_REQUEST";
export const LIST_SERVICES_SUCCESS = "LIST_SERVICES_SUCCESS";
export const ITEM_SERVICE_REQUEST = "ITEM_SERVICE_REQUEST";
export const ITEM_SERVICE_SUCCESS = "ITEM_SERVICE_SUCCESS";
export const ERROR_LIST_REQUEST = "ERROR_LIST_REQUEST";
export const ERROR_ITEM_REQUEST = "ERROR_ITEM_REQUEST";
